GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInVzZXJOYW1lIjoiVGVzdCBOYW1lIiwidXNlckVtYWlsIjoidGVzdEBnbWFpbC5jb20iLCJpYXQiOjE2ODc3ODExNTEsImV4cCI6MTY4Nzc4MTE3MX0.xnLPi0_-YPcWMLjZvKcB0LWVD3iyqMmcsa6kiqLQGaA
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "ananda",
    "email": "ananda@gmail.com",
    "password": "123"
}

###
POST https://app-c8f8ca2d-2b0f-41c7-930c-039bcbaa2e4c.cleverapps.io/login
Content-Type: application/json

    {
        "email": "admin@gmail.com",
        "password": "123"
    }

###
GET https://app-c8f8ca2d-2b0f-41c7-930c-039bcbaa2e4c.cleverapps.io/token

###
DELETE http://localhost:5000/logout


###
Get http://localhost:5000/product
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInVzZXJOYW1lIjoiVGVzdCBOYW1lIiwidXNlckVtYWlsIjoidGVzdEBnbWFpbC5jb20iLCJpYXQiOjE2ODc3ODExOTksImV4cCI6MTY4Nzc4MTIxOX0.0vQLY_Wy_6cvS17atecfEK5g2ohx9FY8upFGG5oQj0w